#include <iostream>
#include <vector>
#include <unordered_map>
#include <fstream>

// Piece of code needed to create a Hashmap with a std::pair as the key (Generated by ChatGPT lol)
namespace std {
    template <>
    struct hash<std::pair<int, int>> {  // Even ChatGPT places the keys here :) 
        size_t operator()(const std::pair<int, int>& p) const {
            // Use a hash function combining the two integers
            size_t h1 = std::hash<int>{}(p.first);
            size_t h2 = std::hash<int>{}(p.second);
            // Combine the hashes using a bitwise operation (e.g., XOR)
            return h1 ^ h2;
        }
    };
}

std::string readInputText(std::string inputText){

    // Read input data from txt file
    std::fstream inputfile;
    std::string inputData;

    inputfile.open(inputText, std::ios::in);
    if (inputfile.is_open()){
        std::string tp;
        while (getline(inputfile, tp)){
            inputData += tp;
            inputData += "\n";
        }
    }
    return inputData;
}